### ISSUE TITLE
Gem version 1.0 not properly tagged

### ISSUE THREAD

**Issue by danielfsbarreto** [trailblazer/trailblazer-test#18]
Hey there!

I was going through https://trailblazer.to/2.1/docs/test.html#test-installation...

At its very beginning, it mentions users should add the following line to their Gemfile:

```
gem 'trailblazer-test', ">= 1.0.0"
```

However, by looking at https://rubygems.org/gems/trailblazer-test, this version wasn't published.

**Comment by apotonick** [comment]
Hi @danielfsbarreto yes, thanks! :beers: We haven't published the final version, yet, because I still have one little bit of API that I'm not sure about. Are you happy with it so far?

**Comment by danielfsbarreto** [comment]
Hey, @apotonick! Thank you for responding so quickly. I am enjoying it so far! Still in early analysis stage, weighting my options, but trailblazer as a whole sounds like a solid ecosystem to work with!

I will keep an eye on this gem and look forward to trying its first stable version!

**Comment by apotonick** [comment]
@danielfsbarreto I would love to hear your feedback on this version! https://trailblazer.to/2.1/docs/test.html#test-operation-unit-tests Pretty convinced that the API won't change a lot.

**Comment by danielfsbarreto** [comment]
Good to know, @apotonick. I will give it a shot,then, and let you know as soon as I have any piece of constructive feedback!
